class Values
{
    class East
    {
        name = "East";
        tooltip = "OPFOR";
        value = 0;
    };
    class Independant
    {
        name = "Independant";
        tooltip = "Independant";
        value = 2;
    };
    class West
    {
        name = "West";
        tooltip = "BLUFOR";
        value = 1;
    };
    class Player
    {
        name = "AnyPlayer";
        tootip = "AnyPlayer";
        value = 3;
    };
};	