name = "Mission Support Foundation"
prefix = "msf"
author = "Zeik Tuvai"

[files]
include = [
  "mod.cpp",
  "../README.md",
  "LICENSE",
  "version*",
]

[hemtt.config]
preset = "Hemtt"

[properties]
author = "Zeik_Tuvai"
url = "https://github.com/zeiktuvai/MSF_Addon"