class TFY_Commander
{
    displayName = "Commander";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\captain_gs.paa";
    role = "TFY_Leader";

    weapons[] = {
        "rhs_weap_m16a4_imod_M203",
    };
    magazines[] = {"rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan", "rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan", "rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",
        "rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan", "rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan", "rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",
        "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen", "SmokeShellGreen",
        "HandGrenade", "HandGrenade", "HandGrenade"
    };
    items[] = {
        "ACE_EarPlugs", "ACE_wirecutter", "ACE_DefusalKit", "ACE_MapTools", "ACE_WaterBottle", "ACE_CableTie", "ACE_CableTie",
        "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", 
        "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_quikclot", "ACE_quikclot",
        "ACE_quikclot", "ACE_quikclot", "ACE_quikclot", "ACE_quikclot", "ACE_quikclot", "ACE_quikclot", "ACE_quikclot",
        "ACE_adenosine", "ACE_adenosine", "ACE_adenosine", "ACE_adenosine", "ACE_adenosine", "ACE_epinephrine", "ACE_epinephrine",
        "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine",
        "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_morphine",
        "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_bloodIV", "ACE_bloodIV", "ACE_bloodIV", "ACE_bloodIV", "ACE_bloodIV", "ACE_bodyBag",
        "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet", "ACE_tourniquet",
        "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint", "ACE_splint",
        "ACE_M26_Clacker", "ACE_IR_Strobe_Item", "acex_intelitems_notepad", "ACE_HandFlare_Green", "ACE_HandFlare_Green"
    };
    linkedItems[] = {
        "rhsusf_iotv_ocp_Squadleader",
        "H_HelmetB_plain_wdl",
        "rhsusf_oakley_goggles_clr",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "NVGogglesB_blk_F",
        "rhsusf_acc_SFMB556",
        "rhsusf_acc_su230"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "B_TacticalPack_rgr";
};
class TFY_Autorifleman
{
    displayName = "Autorifleman";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\corporal_gs.paa";
    role = "TFY_Assault";

    weapons[] = {
        "rhs_weap_m249", "Binocular"
    };
    magazines[] = {
        "rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",
        "rhsusf_100Rnd_556x45_M855_mixed_soft_pouch",
        "rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_coyote",
        "rhsusf_100Rnd_556x45_M855_mixed_soft_pouch_ucp",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "HandGrenade",
        "HandGrenade",
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "rhsusf_opscore_fg_pelt_nsw",
        "V_PlateCarrier1_tna_F",
        "JAS_GPNVG18_Tan_TI",
        "rhsusf_acc_saw_bipod",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "B_AssaultPack_cbr";
};
class TFY_Marksman
{
    displayName = "Marksman";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\sergeant_gs.paa";
    role = "TFY_Recon";

    weapons[] = {
        "rhs_weap_m14ebrri","Binocular","rhsusf_weap_glock17g4"
    };
    magazines[] = {
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_mag_17Rnd_9x19_FMJ",
        "rhsusf_mag_17Rnd_9x19_FMJ",
        "rhsusf_mag_17Rnd_9x19_FMJ",
        "rhsusf_mag_17Rnd_9x19_FMJ",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "rhsusf_20Rnd_762x51_m993_Mag",
        "SmokeShellGreen",
        "SmokeShellRed",
        "HandGrenade",
        "HandGrenade"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "H_HelmetB_camo",
        "V_PlateCarrier2_rgr",
        "JAS_GPNVG18_Tan_TI",
        "rhsusf_acc_anpeq15side_bk",
        "NForce_Atcr_RMR_Top_SkeetIR_Down",
        "rhsusf_acc_harris_bipod",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "B_AssaultPack_tna_F";
};
class TFY_Teamleader
{
    displayName = "Teamleader";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\sergeant_gs.paa";
    role = "TFY_Leader";

    weapons[] = {
        "rhs_weap_m16a4_imod_M203","Rangefinder"
    };
    magazines[] = {
        "rhs_mag_30Rnd_556x45_Mk318_PMAG_Tan",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "HandGrenade",
        "HandGrenade",
        "HandGrenade",
        "1Rnd_HE_Grenade_shell",
        "1Rnd_HE_Grenade_shell",
        "1Rnd_HE_Grenade_shell",
        "1Rnd_HE_Grenade_shell",
        "1Rnd_HE_Grenade_shell",
        "ACE_40mm_Flare_white",
        "rhs_mag_m662_red",
        "1Rnd_SmokeGreen_Grenade_shell",
        "1Rnd_SmokeRed_Grenade_shell"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "rhsusf_opscore_mc_cover_pelt_nsw",
        "rhsusf_iotv_ocp_Squadleader",
        "JAS_GPNVG18_Tan_TI",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "rhsusf_oakley_goggles_clr",
        "rhsusf_acc_SFMB556",
        "rhsusf_acc_su230"
    };
    uniformClass = "rhs_uniform_g3_mc";
    backpack = "rhsusf_assault_eagleaiii_ocp";
};
class TFY_Rifleman
{
    displayName = "Rifleman";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\private_gs.paa";
    role = "TFY_Assault";

    weapons[] = {
        "rhs_weap_hk416d145","Binocular","rhs_weap_M320"
    };
    magazines[] = {
        "HandGrenade",
        "HandGrenade",
        "HandGrenade",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "UGL_FlareGreen_F",
        "rhs_mag_M397_HET",
        "rhs_mag_M397_HET",
        "rhs_mag_M397_HET",
        "ACE_40mm_Flare_green",
        "ACE_40mm_Flare_green",
        "rhs_mag_30Rnd_556x45_Mk318_PMAG",
        "1Rnd_Smoke_Grenade_shell"
        };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "rhsusf_opscore_fg_pelt_nsw",
        "V_PlateCarrier2_tna_F",
        "rhsusf_acc_su230",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "JAS_GPNVG18_Tan_TI"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "rhsusf_assault_eagleaiii_coy";
};
class TFY_Grenadier
{
    displayName = "Grenadier";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\private_gs.paa";
    role = "TFY_Assault";

    weapons[] = {
        "rhs_weap_hk416d145_m320","Binocular"
    };
    magazines[] = {
        "HandGrenade",
        "HandGrenade",
        "HandGrenade",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "1Rnd_Smoke_Grenade_shell",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",        
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "UGL_FlareGreen_F",
        "rhs_mag_M397_HET",
        "rhs_mag_M397_HET",
        "rhs_mag_M397_HET",
        "rhs_mag_M397_HET",
        "rhs_mag_M397_HET",
        "rhs_mag_M397_HET",
        "ACE_40mm_Flare_green",
        "ACE_40mm_Flare_green",
        "rhs_mag_30Rnd_556x45_Mk318_PMAG",
        "1Rnd_Smoke_Grenade_shell"
        };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "rhsusf_opscore_fg_pelt_nsw",
        "V_PlateCarrier2_tna_F",
        "rhsusf_acc_su230",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "JAS_GPNVG18_Tan_TI"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "rhsusf_assault_eagleaiii_coy";
};
class TFY_ATRifleman
{
    displayName = "AT Rifleman";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\private_gs.paa";
    role = "TFY_Spc";

    weapons[] = {
        "rhs_weap_hk416d145","Binocular","launch_MRAWS_green_F"
    };
    magazines[] = {
        "rhs_mag_30Rnd_556x45_Mk318_PMAG",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "MRAWS_HEAT_F",
        "MRAWS_HEAT_F",
        "MRAWS_HEAT_F",
        "MRAWS_HEAT_F",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "HandGrenade",
        "HandGrenade",
        "HandGrenade"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "H_HelmetB_Enh_tna_F",
        "V_PlateCarrier2_tna_F",
        "rhsusf_acc_su230",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "JAS_GPNVG18_Tan_TI",
        "rhs_googles_orange"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "B_Kitbag_rgr";
};
class TFY_AARifleman
{
    displayName = "AA Rifleman";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\private_gs.paa";
    role = "TFY_Spc";

    weapons[] = {
        "rhs_weap_hk416d145","Binocular","launch_I_Titan_F"
    };
    magazines[] = {
        "rhs_mag_30Rnd_556x45_Mk318_PMAG",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "Titan_AA",
        "Titan_AA",
        "Titan_AA",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "SmokeShellGreen",
        "HandGrenade",
        "HandGrenade",
        "HandGrenade"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "H_HelmetB_Enh_tna_F",
        "V_PlateCarrier2_tna_F",
        "rhsusf_acc_su230",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "JAS_GPNVG18_Tan_TI",
        "rhs_googles_orange"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "B_Kitbag_rgr";
};
class TFY_UAVOperator
{
    displayName = "UAV Operator";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\private_gs.paa";
    role = "TFY_Recon";

    weapons[] = {
        "rhs_weap_hk416d145", "rhs_weap_rsp30_red", "Binocular"
    };
    magazines[] = {
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "SmokeShellGreen",
        "SmokeShellRed",
        "HandGrenade",
        "HandGrenade"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_UAVBattery",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint"
    };
    linkedItems[] = {
        "H_HelmetB_tna_F",
        "V_PlateCarrier2_rgr",
        "rhsusf_acc_anpeq15side_bk",
        "optic_DMS",
        "rhsusf_acc_harris_bipod",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "B_UavTerminal",
        "TFAR_anprc152",
        "JAS_GPNVG18_Tan_TI",
        "rhs_googles_orange"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "B_AssaultPack_tna_F";
};
class TFY_VehicleCrewman
{
    displayName = "Vehicle Crewman";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\sergeant_gs.paa";
    role = "TFY_Crew";

    weapons[] = {
        "rhs_weap_hk416d145","Binocular", "rhsusf_weap_m1911a1"
    };
    magazines[] = {
        "rhs_mag_30Rnd_556x45_Mk318_PMAG",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
        "9Rnd_45ACP_Mag",
        "9Rnd_45ACP_Mag",
        "9Rnd_45ACP_Mag",
        "SmokeShellGreen",
        "SmokeShellGreen"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ToolKit"
    };
    linkedItems[] = {
        "H_HelmetCrew_B",
        "V_PlateCarrier2_rgr",
        "rhsusf_acc_su230",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "B_UavTerminal",
        "TFAR_anprc152",
        "JAS_GPNVG18_Tan_TI",
        "G_Tactical_Clear"
    };
    uniformClass = "U_B_HeliPilotCoveralls";
    backpack = "B_TacticalPack_rgr";
};
class TFY_Medic
{
    displayName = "Combat Lifesaver";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\corporal_gs.paa";
    role = "TFY_Support";

    weapons[] = {
        "rhs_weap_mk18","Binocular","rhs_weap_rsp30_red"
    };
    magazines[] = {
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_30Rnd_556x45_Mk318_SCAR",
        "rhs_mag_rsp30_red",
        "SmokeShellGreen",
        "SmokeShellRed",
        "SmokeShellPurple",
        "SmokeShellPurple",
        "HandGrenade",
        "HandGrenade",
        "HandGrenade"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_CableTie"
    };
    linkedItems[] = {
        "H_HelmetB_Light_tna_F",
        "V_TacVestIR_blk",
        "rhsusf_acc_nt4_tan",
        "rhsusf_acc_su230a_c",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "B_UavTerminal",
        "TFAR_anprc152",
        "JAS_GPNVG18_Tan_TI",
        "rhs_googles_clear"
    };
    uniformClass = "U_B_T_Soldier_SL_F";
    backpack = "B_AssaultPack_rgr_Medic";
};
class TFY_Diver_Expl
{
    displayName = "Diver Explosives Spc.";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\sergeant_gs.paa";
    role = "TFY_SF_Diver";

    weapons[] = {
        "arifle_SDAR_F","hgun_P07_snds_F","Rangefinder"
    };
    magazines[] = {
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "30Rnd_556x45_Stanag_red",
        "30Rnd_556x45_Stanag_red",
        "30Rnd_556x45_Stanag_red",
        "16Rnd_9x21_Mag",
        "16Rnd_9x21_Mag",
        "16Rnd_9x21_Mag",
        "SmokeShellBlue",
        "SmokeShellBlue"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV_500",
        "ACE_bodyBag",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "Chemlight_blue",
        "Chemlight_blue",
        "Chemlight_blue",
        "Chemlight_blue",
    };
    linkedItems[] = {
        "rhsusf_opscore_fg_pelt_nsw",
        "V_RebreatherB",
        "JAS_GPNVG18_blk_TI",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "muzzle_snds_L",
        "G_B_Diving"
    };
    uniformClass = "U_B_Wetsuit";
    backpack = "B_FieldPack_blk";
};
class TFY_Diver
{
    displayName = "Assault Diver";
    icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\sergeant_gs.paa";
    role = "TFY_SF_Diver";

    weapons[] = {
        "arifle_SDAR_F","hgun_P07_snds_F","Rangefinder"
    };
    magazines[] = {
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "20Rnd_556x45_UW_mag",
        "30Rnd_556x45_Stanag_red",
        "30Rnd_556x45_Stanag_red",
        "30Rnd_556x45_Stanag_red",
        "16Rnd_9x21_Mag",
        "16Rnd_9x21_Mag",
        "16Rnd_9x21_Mag",
        "SmokeShellBlue",
        "SmokeShellBlue"
    };
    items[] = {
        "ACE_EarPlugs",
        "ACE_wirecutter",
        "ACE_DefusalKit",
        "ACE_MapTools",
        "ACE_WaterBottle",
        "ACE_CableTie",
        "ACE_CableTie",
        "ACE_M26_Clacker",
        "ACE_IR_Strobe_Item",
        "acex_intelitems_notepad",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_fieldDressing",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_packingBandage",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_quikclot",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_elasticBandage",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_adenosine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_epinephrine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_morphine",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV",
        "ACE_bloodIV_500",
        "ACE_bloodIV_500",
        "ACE_bloodIV_500",
        "ACE_bodyBag",
        "ACE_bodyBag",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_tourniquet",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "ACE_splint",
        "Chemlight_blue",
        "Chemlight_blue",
        "Chemlight_blue",
        "Chemlight_blue",
    };
    linkedItems[] = {
        "rhsusf_opscore_fg_pelt_nsw",
        "V_RebreatherB",
        "JAS_GPNVG18_blk_TI",
        "ItemCompass",
        "ACE_Altimeter",
        "ItemMap",
        "ItemGPS",
        "TFAR_anprc152",
        "muzzle_snds_L",
        "G_B_Diving"
    };
    uniformClass = "U_B_Wetsuit";
    backpack = "B_FieldPack_blk";
};
class TFY_MineSpec
{
  displayName = "Mine Specialist";
  icon = "\A3\Ui_f\data\GUI\Cfg\Ranks\sergeant_gs.paa";
  role = "TFY_Support";
  uniformClass = "U_B_T_Soldier_SL_F";
  backpack = "rhsusf_assault_eagleaiii_ocp";
  weapons[] = {"rhs_weap_hk416d145", "Binocular", "Throw", "Put"};
  magazines[] = {"acex_intelitems_notepad", "HandGrenade", "HandGrenade", "rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red", "ATMine_Range_Mag", "rhs_mag_30Rnd_556x45_M855_PMAG_Tracer_Red", "rhs_mag_30Rnd_556x45_M855_PMAG_Tracer_Red", "rhs_mag_30Rnd_556x45_Mk318_PMAG"};
  items[] = {"ACE_EarPlugs", "ACE_wirecutter", "ACE_MapTools", "ACE_DefusalKit", "ACE_M26_Clacker", "ACE_IR_Strobe_Item", "ACE_CableTie", "ACE_CableTie", "ACE_WaterBottle", "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_packingBandage", "ACE_quikclot", "ACE_quikclot", "ACE_quikclot", "ACE_quikclot", "ACE_quikclot", "ACE_bloodIV", "ACE_bodyBag", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_epinephrine", "ACE_morphine", "ACE_morphine", "ACE_morphine", "ACE_tourniquet", "ACE_tourniquet", "ACE_splint", "ACE_splint", "ToolKit", "MineDetector"};
  linkedItems[] = {"V_EOD_olive_F", "rhs_altyn_visordown", "ItemMap", "ItemCompass", "ACE_Altimeter", "rhsusf_radio_anprc152", "ItemGPS", "rhsusf_acc_su230"};
};