colorBackground[] = {0,0,0,0};
colorBackground2[] = {0,0,0,0};
class Attributes
{
    size = 0.9;
    font = "PuristaLight";
};
class ShortcutPos
{
    left = "0";
    top = "0.5 * (pixelH * pixelGrid * 0.50)";
    w = "4 * (pixelW * pixelGrid * 0.50)";
    h = "4 * (pixelH * pixelGrid * 0.50)";
};
class TextPos
{
    left = "4.5 * (pixelW * pixelGrid * 0.50)";
    top = "0";
    right = "0";
    bottom = "0";
};
